 
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vm5C5D3GFpKC6zDVyoLFde

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vm5C5D3GFpKC6zDVyoLFde/projectModule

const data = {
	base: `${"plasmic_tokens_vm5C5D3GFpKC6zDVyoLFde"}`,
	varianted: [],
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
