/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vm5C5D3GFpKC6zDVyoLFde
// Component: 0TS71ob9QO5w

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
	Flex as Flex__,
	MultiChoiceArg,
	PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
	PlasmicIcon as PlasmicIcon__,
	PlasmicImg as PlasmicImg__,
	PlasmicLink as PlasmicLink__,
	PlasmicPageGuard as PlasmicPageGuard__,
	SingleBooleanChoiceArg,
	SingleChoiceArg,
	Stack as Stack__,
	StrictProps,
	Trans as Trans__,
	classNames,
	createPlasmicElementProxy,
	deriveRenderOpts,
	ensureGlobalVariants,
	generateOnMutateForSpec,
	generateStateOnChangeProp,
	generateStateOnChangePropForCodeComponents,
	generateStateValueProp,
	get as $stateGet,
	hasVariant,
	initializeCodeComponentStates,
	initializePlasmicStates,
	makeFragment,
	omit,
	pick,
	renderPlasmicSlot,
	set as $stateSet,
	useCurrentUser,
	useDollarState,
	usePlasmicTranslator,
	useTrigger,
	wrapWithClassName,
} from "@plasmicapp/react-web";
import {
	DataCtxReader as DataCtxReader__,
	useDataEnv,
	useGlobalActions,
} from "@plasmicapp/react-web/lib/host";

import { TimelineWrapper } from "@plasmicpkgs/react-twitter-widgets";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: vm5C5D3GFpKC6zDVyoLFde/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: vm5C5D3GFpKC6zDVyoLFde/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicTest.module.css"; // plasmic-import: 0TS71ob9QO5w/css

const emptyProxy: any = new Proxy(() => "", {
	get(_, prop) {
		return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
	},
});

function wrapQueriesWithLoadingProxy($q: any): any {
	return new Proxy($q, {
		get(target, queryName) {
			const query = target[queryName];
			return !query || query.isLoading || !query.data ? emptyProxy : query;
		},
	});
}

export type PageCtx = {
	pageRoute: string;
	pagePath: string;
	params: Record<string, string | string[] | undefined>;
	query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
	return {
		title: "test",

		openGraph: {
			title: "test",
		},
		twitter: {
			card: "summary" as const,
			title: "test",
		},
	};
}

createPlasmicElementProxy;

export type PlasmicTest__VariantMembers = {};
export type PlasmicTest__VariantsArgs = {};
type VariantPropType = keyof PlasmicTest__VariantsArgs;
export const PlasmicTest__VariantProps = new Array<VariantPropType>();

export type PlasmicTest__ArgsType = {};
type ArgPropType = keyof PlasmicTest__ArgsType;
export const PlasmicTest__ArgProps = new Array<ArgPropType>();

export type PlasmicTest__OverridesType = {
	root?: Flex__<"div">;
	h1?: Flex__<"h1">;
	rectangle1?: Flex__<"div">;
	timeline?: Flex__<typeof TimelineWrapper>;
	text?: Flex__<"div">;
};

export interface DefaultTestProps {}

const $$ = {};

function useNextRouter() {
	try {
		return useRouter();
	} catch {}
	return undefined;
}

function PlasmicTest__RenderFunc(props: {
	variants: PlasmicTest__VariantsArgs;
	args: PlasmicTest__ArgsType;
	overrides: PlasmicTest__OverridesType;
	forNode?: string;
}) {
	const { variants, overrides, forNode } = props;

	const args = React.useMemo(
		() =>
			Object.assign({}, Object.fromEntries(Object.entries(props.args).filter(([_, v]) => v !== undefined))),
		[props.args],
	);

	const $props = {
		...args,
		...variants,
	};

	const __nextRouter = useNextRouter();

	const $ctx = useDataEnv?.() || {};
	const refsRef = React.useRef({});
	const $refs = refsRef.current;

	const pageMetadata = generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), $ctx as PageCtx);

	const styleTokensClassNames = _useStyleTokens();

	return (
		<React.Fragment>
			<Head>
				<meta name="twitter:card" content="summary" />
				<title key="title">{pageMetadata.title}</title>
				<meta key="og:title" property="og:title" content={pageMetadata.title} />
				<meta key="twitter:title" property="twitter:title" content={pageMetadata.title} />
			</Head>

			<style>{`
        body {
          margin: 0;
        }
      `}</style>

			<div className={"plasmic_page_wrapper"}>
				<div
					data-plasmic-name={"root"}
					data-plasmic-override={overrides.root}
					data-plasmic-root={true}
					data-plasmic-for-node={forNode}
					className={classNames(
						"all",
						"root_reset_vm5C5D3GFpKC6zDVyoLFde",
						"plasmic_default_styles",
						"plasmic_mixins",
						styleTokensClassNames,
						sty.root,
					)}
				>
					<h1
						data-plasmic-name={"h1"}
						data-plasmic-override={overrides.h1}
						className={classNames("all", "h1", "h1__vm5C5", "__wab_text", sty.h1)}
					>
						{"You won't believe what happens next."}
					</h1>
					<div className={classNames("all", sty.freeBox___3Fyne)} />

					<div
						data-plasmic-name={"rectangle1"}
						data-plasmic-override={overrides.rectangle1}
						className={classNames("all", sty.rectangle1)}
					/>

					<TimelineWrapper
						data-plasmic-name={"timeline"}
						data-plasmic-override={overrides.timeline}
						className={classNames("__wab_instance", sty.timeline)}
						url={"https://twitter.com/plasmicapp"}
					/>

					<div
						data-plasmic-name={"text"}
						data-plasmic-override={overrides.text}
						className={classNames("all", "__wab_text", sty.text)}
					>
						{
							'import "../../components/plasmic/blank_project/plasmic.css"; // plasmic-import: vm5C5D3GFpKC6zDVyoLFde/projectcss'
						}
					</div>
					<div className={classNames("all", sty.freeBox__yjrvk)} />
				</div>
			</div>
		</React.Fragment>
	) as React.ReactElement | null;
}

const PlasmicDescendants = {
	root: ["root", "h1", "rectangle1", "timeline", "text"],
	h1: ["h1"],
	rectangle1: ["rectangle1"],
	timeline: ["timeline"],
	text: ["text"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> = (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
	root: "div";
	h1: "h1";
	rectangle1: "div";
	timeline: typeof TimelineWrapper;
	text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<PlasmicTest__OverridesType, DescendantsType<T>>;
type NodeComponentProps<T extends NodeNameType> =
	// Explicitly specify variants, args, and overrides as objects
	{
		variants?: PlasmicTest__VariantsArgs;
		args?: PlasmicTest__ArgsType;
		overrides?: NodeOverridesType<T>;
	} &
		// Specify variants directly as props
		Omit<PlasmicTest__VariantsArgs, ReservedPropsType> &
		// Specify args directly as props
		Omit<PlasmicTest__ArgsType, ReservedPropsType> &
		// Specify overrides for each element directly as props
		Omit<NodeOverridesType<T>, ReservedPropsType | VariantPropType | ArgPropType> &
		// Specify props for the root element
		Omit<
			Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
			ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
		>;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
	type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
	const func = function <T extends PropsType>(props: T & StrictProps<T, PropsType>) {
		const { variants, args, overrides } = React.useMemo(
			() =>
				deriveRenderOpts(props, {
					name: nodeName,
					descendantNames: PlasmicDescendants[nodeName],
					internalArgPropNames: PlasmicTest__ArgProps,
					internalVariantPropNames: PlasmicTest__VariantProps,
				}),
			[props, nodeName],
		);
		return PlasmicTest__RenderFunc({
			variants,
			args,
			overrides,
			forNode: nodeName,
		});
	};
	if (nodeName === "root") {
		func.displayName = "PlasmicTest";
	} else {
		func.displayName = `PlasmicTest.${nodeName}`;
	}
	return func;
}

export const PlasmicTest = Object.assign(
	// Top-level PlasmicTest renders the root element
	makeNodeComponent("root"),
	{
		// Helper components rendering sub-elements
		h1: makeNodeComponent("h1"),
		rectangle1: makeNodeComponent("rectangle1"),
		timeline: makeNodeComponent("timeline"),
		text: makeNodeComponent("text"),

		// Metadata about props expected for PlasmicTest
		internalVariantProps: PlasmicTest__VariantProps,
		internalArgProps: PlasmicTest__ArgProps,

		pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
			pageRoute: "/test",
			pagePath: "/test",
			params: {},
			query: {},
		}),
	},
);

export default PlasmicTest;
/* prettier-ignore-end */
