/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: itBdcjth19Wasd6ngAYxWR

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: itBdcjth19Wasd6ngAYxWR/projectModule

const data = {
	base: `${"plasmic_tokens_itBdcjth19Wasd6ngAYxWR"}`,
	varianted: [],
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
